market/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
   
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views 
from django.conf import settings
from django.conf.urls.static import static
app_name = "polls"

urlpatterns = [
    path('nfts/', views.nft_list, name='nft_list'),
    path("nfts/<uuid:nft_id>/", views.nft_detail, name="nft_detail"),
    path("collections/<uuid:collection_id>/", views.collection_detail, name="collection_detail"),
    path('register/', views.user_registration, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    path('index/', views.index, name='index'),
    path('upload/', views.image_upload_view)
]

polls/models.py
# Create your models here.
from django.db import models
import uuid

class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')
    def __str__(self):
        return self.title

class User(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)# буде генеруватися випадковий унікальний UUID. не доступне для редагування через Django Admin
    wallet_address = models.CharField(max_length=255, unique=True)
    username = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)  #null=True → у базі даних поле може бути NULL
    created_at = models.DateTimeField(auto_now_add=True) #auto_now_add=True → автоматично встановлює дату створення.
    

    def __str__(self):
        return self.username

class Collection(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="collections")
    description = models.TextField(null=True, blank=True) #null=True, blank=True → робить поле необов’язковим.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class NFT(models.Model):
    STATUS_CHOICES = [
        ('for_sale', 'For Sale'),
        ('sold', 'Sold'),           # визначає можливі значення, які може мати статус NFT.
        ('delisted', 'Delisted'),
    ]   

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) #  буде генеруватися випадковий унікальний UUID. не доступне для редагування через Django Admin
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_nfts")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="owned_nfts")#null=True, blank=True → робить поле необов’язковим.
    collection = models.ForeignKey(Collection, on_delete=models.SET_NULL, null=True, blank=True, related_name="nfts")#null=True, blank=True → робить поле необов’язковим.
    metadata = models.URLField()  #зберігає URL-адресу.
    price = models.DecimalField(max_digits=18, decimal_places=8, null=True, blank=True)
    minted_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='for_sale')

    def __str__(self):
        return self.name

class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nft = models.ForeignKey(NFT, on_delete=models.CASCADE, related_name="transactions")
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="sales")
    buyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="purchases") 
    amount = models.DecimalField(max_digits=18, decimal_places=8) #max_digits=18 → Загальна максимальна кількість цифр (включно з десятковими та цілими).
    tx_hash = models.CharField(max_length=255, unique=True) # унікальність значень
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction {self.tx_hash}"

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from .models import Image

class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ('title', 'image')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'enter your password'}),
        help_text="",
        label="Password"
    )
    
    # Додаємо поле для підтвердження пароля
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'confirm your password'}),
        label="Confirm Password"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'enter your username',
                'autofocus': True
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'enter your email',
                'required': True
            }),
        }
        labels = {
            'username': 'Username',
            'email': 'Email',
        }

    # Валідація пароля
    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password, self.instance)
        except ValidationError as e:
            raise forms.ValidationError(list(e.messages))
        
        return password

    # Валідація підтвердження пароля
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

polls/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import NFT, Collection, User
from .forms import ImageForm

def upload(request):
    return render(request, "polls/upload.html")

def nft_list(request):
    nfts = NFT.objects.all()
    return render(request, "polls/nft_list.html", {"nfts": nfts})

def index(request):
    return render(request, "polls/index.html")

def nft_detail(request, nft_id):
    """Детальна інформація про NFT"""
    nft = get_object_or_404(NFT, id=nft_id)
    return render(request, "nft_detail.html", {"nft": nft})

def collection_detail(request, collection_id):
    """Детальна інформація про колекцію NFT"""
    collection = get_object_or_404(Collection, id=collection_id)
    return render(request, "collection_detail.html", {"collection": collection})


from django.shortcuts import render, redirect
from django.contrib import messages  # Для повідомлень
from .forms import UserRegistrationForm
def user_registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()  # Зберігаємо нового користувача
            messages.success(request, 'Your account has been created successfully!')
            # Перенаправляємо на сторінку входу
    else:
        form = UserRegistrationForm()
    return render(request, 'polls/register.html', {'form': form})
    


def image_upload_view(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            return render(request, 'polls\index2.html', {'form': form, 'img_obj': img_obj})
    else:
        form = ImageForm()    
        return render(request, 'polls\index2.html', {'form': form})

market/polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ukr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Krytixlopchi Shop</title>
    <style></style>
    <script src="{% static 'polls/scripts/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}" />
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="#"
          ><img
            src="http://127.0.0.1:8000/media/images/logo.png"
            alt=""
            width="70"
            height="70"
        /></a>
        <div>krytixlopchi</div>
      </div>
      <nav>
        <ul>
          <li class="dropdown">
            <button>
              <img
                src="http://127.0.0.1:8000/media/images/basket.png"
                alt=""
                width="40px"
                height="40px"
              />
            </button>
          </li>
          <li><a href="{% url 'polls:login' %}">Profile</a></li>
          <li><a href="#">Collections</a></li>
          <li><a href="#">Popular</a></li>
          <li><a href="#">Contacts</a></li>
        </ul>
      </nav>
    </header>

    <section class="banner" id="banner">
      <div class="banner-content">
        <h2>Welcome to krytixlopchi NFT Shop!!</h2>
        <a href="#" class="btn">Shop Now!</a>
      </div>
    </section>

    <section class="categories">
      <h2>Categories</h2>
      <div class="category-list">
        <div class="category-item">
          <a href="#"
            ><img src="imgs/categories_imgs/category_art.png" alt="Art NFT"
          /></a>
          <h3>Art</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img src="imgs/categories_imgs/category_music.png" alt="Music NFT"
          /></a>

          <h3>Music</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_games.png"
              alt="Gaming NFT"
          /></a>

          <h3>Games</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_videos.png"
              alt="Videos NFT"
          /></a>

          <h3>Videos</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_collectibles.png"
              alt="Collectibles NFT"
          /></a>

          <h3>Collectibles</h3>
        </div>
      </div>
    </section>

    <section class="popular">
      <h2>Popular Collections</h2>
      <div class="popular-list">
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_1.png"
              alt="NFT Collection 1"
          /></a>

          <h3>Collection 1</h3>
        </div>
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_2.png"
              alt="sNFT Collection 2"
          /></a>

          <h3>Collection 2</h3>
        </div>
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_3.png"
              alt="NFT Collection 3"
          /></a>

          <h3>Collection 3</h3>
        </div>
      </div>
    </section>
    <section class="about">
      <h2>Про нас</h2>
      <p>Ми – платформа NFT, що об'єднує митців та колекціонерів.</p>
    </section>
  
  </body>
</html>

market/polls/templates/polls/index2.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Upload</button>
</form>
{% if img_obj %}
<h3>Succesfully uploaded : {{img_obj.title}}</h3>
<img src="{{ img_obj.image.url}}" alt="connect" style="max-height: 300px" />
{% endif %}

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ukr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Krytixlopchi Shop</title>
    <style></style>
    <script src="{% static 'polls/scripts/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}" />
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="#"
          ><img
            src="http://127.0.0.1:8000/media/images/logo.png"
            alt=""
            width="70"
            height="70"
        /></a>
        <div>krytixlopchi</div>
      </div>
      <nav>
        <ul>
          <li class="dropdown">
            <button>
              <img
                src="http://127.0.0.1:8000/media/images/basket.png"
                alt=""
                width="40px"
                height="40px"
              />
            </button>
          </li>
          <li><a href="{% url 'polls:login' %}">Profile</a></li>
          <li><a href="#">Collections</a></li>
          <li><a href="#">Popular</a></li>
          <li><a href="#">Contacts</a></li>
        </ul>
      </nav>
    </header>

    <section class="banner" id="banner">
      <div class="banner-content">
        <h2>Welcome to krytixlopchi NFT Shop!!</h2>
        <a href="#" class="btn">Shop Now!</a>
      </div>
    </section>

    <section class="categories">
      <h2>Categories</h2>
      <div class="category-list">
        <div class="category-item">
          <a href="#"
            ><img src="imgs/categories_imgs/category_art.png" alt="Art NFT"
          /></a>
          <h3>Art</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img src="imgs/categories_imgs/category_music.png" alt="Music NFT"
          /></a>

          <h3>Music</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_games.png"
              alt="Gaming NFT"
          /></a>

          <h3>Games</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_videos.png"
              alt="Videos NFT"
          /></a>

          <h3>Videos</h3>
        </div>
        <div class="category-item">
          <a href="#"
            ><img
              src="imgs/categories_imgs/category_collectibles.png"
              alt="Collectibles NFT"
          /></a>

          <h3>Collectibles</h3>
        </div>
      </div>
    </section>

    <section class="popular">
      <h2>Popular Collections</h2>
      <div class="popular-list">
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_1.png"
              alt="NFT Collection 1"
          /></a>

          <h3>Collection 1</h3>
        </div>
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_2.png"
              alt="sNFT Collection 2"
          /></a>

          <h3>Collection 2</h3>
        </div>
        <div class="popular-item">
          <a href="#"
            ><img
              src="imgs/collections_imgs/collection_3.png"
              alt="NFT Collection 3"
          /></a>

          <h3>Collection 3</h3>
        </div>
      </div>
    </section>
    <section class="about">
      <h2>Про нас</h2>
      <p>Ми – платформа NFT, що об'єднує митців та колекціонерів.</p>
    </section>
    <section class="team">
      <h2>Наша команда</h2>
      <div class="team-members">
        <div class="team-member">
          <img src="imgs/team_member1.png" alt="Team Member 1" />
          <h3>Олексій - backend developer</h3>
        </div>
        <div class="team-member">
          <img src="imgs/team_member2.png" alt="Team Member 2" />
          <h3>Євген - main frontend developer</h3>
        </div>
        <div class="team-member">
          <img src="imgs/team_member3.png" alt="Team Member 3" />
          <h3>Сергій - desighner and frontend developer</h3>
        </div>
      </div>
    </section>
  </body>
</html>

polls/templates/polls/index2.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Upload</button>
</form>
{% if img_obj %}
<h3>Succesfully uploaded : {{img_obj.title}}</h3>
<img src="{{ img_obj.image.url}}" alt="connect" style="max-height: 300px" />
{% endif %}

polls/templates/polls/login.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Log in</title>
    <link rel="stylesheet" href="{% static 'polls/css/login_style.css' %}" />
  </head>
  <body>
    <div class="login-container">
      <div class="logo">
        <div class="logo-text">krytix</div>
        <a href="{% url 'polls:index' %}">
          <img
            src="http://127.0.0.1:8000/media/images/logo.png"
            alt="Logo"
            width="70px"
            height="70px"
          />
        </a>
        <div class="logo-text">lopchi</div>
      </div>
      <h2>Log In</h2>
      <form method="POST" class="login-form">
        {% csrf_token %} {% if form.errors %}
        <div class="alert alert-danger">
          Неправильний логін або пароль. Спробуйте ще раз.
        </div>
        {% endif %}

        <label for="id_username">Login</label>
        <input
          type="text"
          id="id_username"
          name="username"
          required
          placeholder="enter your login"
        />

        <label for="id_password">Password</label>
        <input
          type="password"
          id="id_password"
          name="password"
          required
          placeholder="enter your password"
        />

        <button type="submit" class="login-btn">Enter</button>

        <div class="signup-link">
          <p>
            Have no account yet?
            <a href="{% url 'polls:register' %}">Sign up</a>
          </p>
        </div>
        <div class="signup-link">
          <a href="#">Log in with email</a>
        </div>
      </form>
    </div>
  </body>
</html>

polls/templates/polls/nft_detail.html
<h1>{{ nft.name }}</h1>
<p>Description: {{ nft.description }}</p>
<p>Created by: {{ nft.creator.username }}</p>
<p>Owned by: {{ nft.owner.username }}</p>
<p>Price: {{ nft.price }} ETH</p>
<p>Status: {{ nft.get_status_display }}</p>
<a href="{% url 'marketplace:nft_list' %}">Back to list</a>

polls/templates/polls/nft_list.html
<!-- polls/templates/polls/nft_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NFT List</title>
</head>
<body>
    <h2>Список NFT</h2>
    <ul>
        {% for nft in nfts %}
            <li>{{ nft.name }}</li>
        {% empty %}
            <li>Немає NFT</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/register.html
<!-- polls/templates/polls/register.html -->
{% load static %}
<!DOCTYPE html>
<html lang="uk">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'polls/css/register.css' %}" />
  </head>
  <body>
    <div class="login-container">
      <div class="logo">
        <div class="logo-text">krytix</div>
        <a href="{% url 'polls:index' %}">
          <!-- Змініть на ваш головний URL -->
          <img
            src="http://127.0.0.1:8000/media/images/logo.png"
            alt=""
            width="70px"
            height="70px"
          />
        </a>
        <div class="logo-text">lopchi</div>
      </div>
      <h2>Sign up</h2>
      <form method="POST" class="login-form">
        {% csrf_token %} {% if form.errors %}
        <div class="alert alert-danger">
          {% for field, errors in form.errors.items %} {% for error in errors %}
          {{ error }}<br />
          {% endfor %} {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
          <label for="id_username">Username</label>
          <div class="input">{{ form.username }}</div>
        </div>

        <div class="form-group">
          <label for="id_email">Email</label>
          <div class="input">{{ form.email }}</div>
        </div>

        <div class="form-group">
          <label for="id_password">Password</label>
          <div class="input">{{ form.password }}</div>
        </div>

        <button type="submit" class="login-btn">Enter</button>

        <div class="signup-link">
          <p>
            already have an account?
            <a href="{% url 'polls:login' %}">Log in</a>
            <!-- Додайте URL для входу -->
          </p>
        </div>
      </form>
    </div>
  </body>
</html>